### ISSUE TITLE
Jira version 8.20.5 - unable to run

### ISSUE THREAD

**Issue by andersvold** [SethSilverBeard/jira-awesomizer-defaults#3]
Hi, I can't make jira-awesomizer work with Jira anymore.
I am currently on Jira version 8.20.5 according to the head-tag in HTML

**Comment by SethSilverBeard** [comment]
Thanks for letting me know! I'm looking into it.

**Comment by SethSilverBeard** [comment]
Updated for version 8.22 of JIRA. Thanks for letting me know as I had no idea it was broken - I don't interface with JIRA on a daily basis anymore. 

Lemme know if you find anything else.
